name: image_picker_example
description: Demonstrates how to use the image_picker plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  video_player:
    git:
      url: https://github.com/wittech/plugins.git
      path: packages/video_player
  flutter:
    sdk: flutter
  image_picker:
    path: ../

flutter:
  uses-material-design: true

